---
title: "Untitled"
author: "Anshul Sinha"
date: '2023-12-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(microViz)
library(dplyr)
library(tidyr)
library(phyloseq)
library(vegan)
```

```{r}
rm(list = ls())

virome_metadata <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/virome_metadata.csv", header = TRUE)
```




```{r}
#Samtools from the L-B prophage set 
#Now incorporating slightly new analyses in 11_2025 including ensuring I import the samtools correctly

samtools <- read.table("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/samtools/concatenated_samtools.tsv", header = FALSE, sep = "\t")
#same number of rows as /home/asinha23/projects/rrg-corinnem/asinha23/omm12_DSS_2_11_2023/virome/bowtie_v_LB_prophages/samtools/concat_samtools and same size



colnames(samtools) <- c("contig_name_filename", "startpos", "endpos", "numreads", "covbases", "coverage",  "meandepth", "meanbaseq", "meanmapq")

prophage_mapper <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/prophage_mapper.csv")
samtools
prophage_mapper

# Split column by comma
df_split <- strsplit(samtools$contig_name_filename, ":")

# Create new columns for each split part
samtools$filename <- sapply(df_split, "[[", 1)
samtools$contigname <- sapply(df_split, "[[", 2)



#remove unecessary part of filename with "sam_tools_cov"
samtools$filename <- sub("^(([^_]*_){2}[^_]*)_.*", "\\1", samtools$filename)
samtools




prophage_mapper



# Define the names of the prophages that will be changed to "0" reads : Montmirail, Villandry, Maintenon, Chantilly, CP065315.1_Flavonifractor_plautii_strain_YL31_chromosome_fragment_37



#prophages_to_change <- c("CP065321.1_Acutalibacter_muris_strain_KB18_chromosome_fragment_51", "CP065314.1_Enterocloster_clostridioformis_strain_YL32_chromosome_fragment_20", "CP065314.1_Enterocloster_clostridioformis_strain_YL32_chromosome_fragment_21", "CP065314.1_Enterocloster_clostridioformis_strain_YL32_chromosome_fragment_24", "ON453901.1_E_Clostridium_phage_Saumur__complete_genome", "CP065314.1_Enterocloster_clostridioformis_strain_YL32_chromosome_fragment_44", "CP065314.1_Enterocloster_clostridioformis_strain_YL32_chromosome_fragment_74", "CP065317.1_Enterococcus_faecalis_strain_KB1_chromosome_fragment_40", "CP065312.1_Blautia_pseudococcoides_strain_YL58_chromosome_fragment_25","CP065312.1_Blautia_pseudococcoides_strain_YL58_chromosome_fragment_53", "CP065315.1_Flavonifractor_plautii_strain_YL31_chromosome_fragment_9", "CP065315.1_Flavonifractor_plautii_strain_YL31_chromosome_fragment_20", "ON453905.1_Flavonifractor_phage_Cormatin__complete_genome", "ON453894.1_Akkermansia_phage_Chambord__partial_genome", "ON453896.1_Akkermansia_phage_Moulinsart__complete_genome", "CP065313.1_Turicimonas_muris_strain_YL45_chromosome_fragment_14",  "CP065318.1_Limosilactobacillus_reuteri_strain_I49_chromosome_fragment_1", "ON453897.1_Bacteroides_phage_Versailles__complete_genome", "CP065320.1_Clostridium_innocuum_strain_I46_chromosome_fragment_71", "ON453899.1_Clostridium_phage_Amboise__complete_genome","ON453893.1_Acutalibacter_phage_Fontainebleau__complete_genome", "ON453903.1_Flavonifractor_phage_Castelnaud__complete_genome", "ON453904.1_Flavonifractor_phage_Chenonceau__complete_genome")

#remove leading spaces 
samtools$contigname <- trimws(samtools$contigname, "left")


samtools1 <- left_join(prophage_mapper,samtools, by="contigname")


#stockdale cutoffs

#<5kb
samtools5 <- samtools1[samtools1$length < 5000,]

samtools5 <- samtools5[samtools5$coverage > 50,]






#between 5 and 20
samtools5_20 <- samtools1[samtools1$length >= 5000 ,]
samtools5_20_2 <- samtools5_20[samtools5_20$length < 20000,]



 samtools5_20 <- samtools5_20_2[samtools5_20_2$coverage > 30,]


 
#Above 20 # basically only this step matters because all the other prophages are < 20 Kb
 
 samtools20.1 <- samtools1[samtools1$length >= 20000,]
samtools20 <- samtools20.1[samtools20.1$coverage > 10,]


samtools_final <- rbind(samtools5, samtools5_20, samtools20)
samtools_final




#for sanity check: 

samtools_final_amboise <- samtools_final[samtools_final$Name == "Amboise",]
mean(samtools_final_amboise$meanmapq)
min(samtools_final_amboise$meanmapq)
median(samtools_final_amboise$meanmapq)









```





```{r}
#read in metadata 

virome_metadata <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/virome_metadata.csv", header = TRUE)


#to help name prophages properly 

prophage_mapper <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/prophage_mapper.csv")
```




```{r}
#I want to calculate the % rel abundance 
#step1 - calculate the mean depth sum for each sample 

library(dplyr)

  df_relab1_test <- samtools_final %>%
    dplyr::group_by(filename) %>%
   dplyr::summarise(sum_depth = sum(meandepth), contig_name_filename, meandepth, numreads, contigname)
  
  
df_relab1_test$relab <- df_relab1_test$meandepth/df_relab1_test$sum_depth



 #sanity check: 
 df_relab1 <- samtools_final %>%
  dplyr::group_by(filename) %>%
  dplyr::mutate(
    sum_depth = sum(meandepth),           # total depth per filename
    relab = meandepth / sum_depth         # relative abundance per contig
  ) %>%
  ungroup()
 
 df_relab1 <- df_relab1 %>%
select(filename, contig_name_filename, meandepth, numreads, sum_depth, contigname, relab)
 

# sanity check values line up with samtools 
samtools_final
df_relab1 
df_relab1_test

#Confirms that my processing works either way (mutate and summarize dont change values )
df1_sub <- samtools_final %>% dplyr::select(contig_name_filename, meandepth, numreads)
df2_sub <- df_relab1 %>% dplyr::select(contig_name_filename, meandepth, numreads)
df3_sub <- df_relab1_test %>% dplyr::select(contig_name_filename, meandepth, numreads)

df1_sub <- df1_sub %>% dplyr::rename(meandepth_df1 = meandepth, numreads_df1 = numreads)
df2_sub <- df2_sub %>% dplyr::rename(meandepth_df2 = meandepth, numreads_df2 = numreads)
df3_sub <- df3_sub %>% dplyr::rename(meandepth_df3 = meandepth, numreads_df3 = numreads)


comparison <- df1_sub %>%
  full_join(df2_sub, by = "contig_name_filename") %>%
  full_join(df3_sub, by = "contig_name_filename")





comparison <- comparison %>%
  mutate(
    meandepth_identical = (meandepth_df1 == meandepth_df2) & (meandepth_df1 == meandepth_df3),
    numreads_identical  = (numreads_df1 == numreads_df2) & (numreads_df1 == numreads_df3)
  )

#####

df_relab <- left_join(virome_metadata, df_relab1, by = "filename")
df_relab <- left_join(df_relab, prophage_mapper, by = "contigname")


# Create a custom color palette with 6 shades
custom_palette <- c("#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a", "#b15928", "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f", "#cab2d6", "#ffff99", "#636363")

# Add a new column to your dataframe to specify the fill color for each name
df_relab$fill_color <- factor(df_relab$Name, levels = unique(df_relab$Name))

library(ggplot2)
 #Grouping dataframe by treatment and family and summing relative abundances within each subgroup 
plot_df <- ggplot(df_relab , aes(fill= interaction(Host, fill_color), y= df_relab$meandepth, x=factor(df_relab$filename))) +
labs(x="Sample") + labs(y="Relative abundance") + labs(fill="family") + 
geom_bar(position = "fill",stat ="identity")  +
theme(axis.text.x=element_text(angle=90,hjust=1)) +
    scale_fill_manual(values = custom_palette) 


plot_df + theme_classic() +
  theme(text=element_text(family="Arial", face="bold", size=15)) + theme(axis.text.x = element_text(size = 3)) + 
  
  theme(legend.text = element_text(size = 2),
        legend.title = element_text(size = 2)) +
 facet_wrap(~Treatment + Day, scales = "free")+ theme(strip.text = element_text(size = 3))


#write.csv(df_relab, "/Users/anshul.sinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome /lb_prophages_list_analyses/samtools/relab.csv")


#Sort 


df_sorted <- df_relab %>%
  arrange(desc(relab))
```

```{r}
#subset just for phage Amboise 
df_relab

df_relab_amboise <- df_relab[df_relab$contigname == "ON453899.1_Clostridium_phage_Amboise__complete_genome",]

write.csv(df_relab_amboise, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/amboise.csv")


df_relab
#subset Maintenon 

df_relab_maintenon <- df_relab[df_relab$contigname == "ON453900.1_Clostridium_phage_Maintenon__complete_genome",]

write.csv(df_relab_maintenon, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/maintenon.csv")




#Calculate the relative abundance ratio between amboise and maintenon 

df_relab_amboise$amboise <- df_relab_amboise$relab
df_relab_maintenon$maintenon <- df_relab_maintenon$relab



df_relab_amboise2 <- df_relab_amboise %>%
  select(Day, filename, amboise)

df_relab_maintenon2 <- df_relab_maintenon %>%
    select(Day, filename, maintenon)

comb_c_innoc_phages <- left_join(df_relab_amboise2, df_relab_maintenon2, by = "filename")

comb_c_innoc_phages$amb_main_ratio <- comb_c_innoc_phages$amboise/comb_c_innoc_phages$maintenon

write.csv(comb_c_innoc_phages, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/amboise_maintenon_ratio_relab.csv")



#Calculate the relative abundance of verasilles    
df_relab_versailles <- df_relab[df_relab$contigname == "ON453897.1_Bacteroides_phage_Versailles__complete_genome",]

sort(df_relab_versailles$relab)
 
df_relab_versailles




#Calculate the relative abundance of Villandry
df_relab_villandry <- df_relab[df_relab$contigname == "ON453902.1_E_Clostridium_phage_Villandry__complete_genome",]

sort(df_relab_villandry$relab)
 
df_relab_villandry


write.csv(df_relab_villandry, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/villandry.csv")

#Calculate the relative abundance of Saumur 
df_relab_saumur <- df_relab[df_relab$contigname == "ON453901.1_E_Clostridium_phage_Saumur__complete_genome",]

sort(df_relab_saumur$relab)
 
write.csv(df_relab_saumur, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/saumur.csv")


#Calculate the relative abundance of Castelnaud 
df_relab_casteldnaud <- df_relab[df_relab$contigname == "ON453903.1_Flavonifractor_phage_Castelnaud__complete_genome",]

sort(df_relab_casteldnaud$relab)
 
write.csv(df_relab_casteldnaud, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/relative_abundance_figures/castelnaud.csv")







```

```{r}
# Plot the relative abundance of different phages

# Plot Amboise
#filter for the days 0,8,9,12,19 - basically remove 1 and 7
#make a function to remove 1 and 7 from the plot


remove_1_7 <- function(df) {
  
 df <- df[df$Days_Post_DSS != 1 & df$Days_Post_DSS != 7,]
  
  df
  
}
   
   
   
df_relab_amboise_1 <- remove_1_7(df_relab_amboise)
df_relab_maintenon_1 <- remove_1_7(df_relab_maintenon)
df_relab_villandry_1 <- remove_1_7(df_relab_villandry)
df_relab_saumur_1 <- remove_1_7(df_relab_saumur)
df_relab_casteldnaud_1 <- remove_1_7(df_relab_casteldnaud)



#df_relab_amboise_1 <- df_relab_amboise[df_relab_amboise$Days_Post_DSS != 1 & df_relab_amboise$Days_Post_DSS != 7,]





ggplot(df_relab_amboise_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  scale_y_log10() +
  labs(title = "Relative Abundance Amboise",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()



ggplot(df_relab_amboise_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  labs(title = "Relative Abundance Amboise",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()



ggplot(df_relab_maintenon_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  scale_y_log10() +
  labs(title = "Relative Abundance Maintenon",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()


ggplot(df_relab_villandry_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  scale_y_log10() +
  labs(title = "Relative Abundance Villandry",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()

ggplot(df_relab_saumur_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  scale_y_log10() +
  labs(title = "Relative Abundance Saumur",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()








##CASTELNAUD - Just isolating the effects of D3
library(ggplot2)

ggplot(df_relab_casteldnaud_1, aes(x = Days_Post_DSS, y = relab, color = Treatment)) +
  geom_jitter(
    position = position_jitterdodge(dodge.width = 0.6, jitter.width = 0.1),
    alpha = 0.6,
    size = 4  # Adjust the size of the points
  ) +
  geom_point(data = subset(df_relab_casteldnaud_1, Mouse == "D3"),
             aes(x = Days_Post_DSS, y = relab),
             color = "black",  # Outline color
             size = 4.5,       # Adjust the size of the circled points (slightly larger than the jittered points)
             shape = 21,       # Circle with fill
             fill = NA,        # No fill color
             stroke = 1.5) +   # Thickness of the outline
  labs(title = "Relative Abundance Castelnaud",
       x = "Days Post-DSS",
       y = "Relative Abundance") +
  theme_minimal()



 













```



```{r}
#calculate RPKM - for comparison use for Amboise: Maintenon ratio #following instructions here: https://www.rna-seqblog.com/rpkm-fpkm-and-tpm-clearly-explained/

samtools_rpkm <- samtools  %>%
    group_by(filename) %>%
    dplyr::summarise(sum_reads = sum(numreads), endpos, numreads, contigname)

#1 Count up the total reads in a sample and divide that number by 1,000,000 – this is our “per million” scaling factor.

samtools_rpkm$reads_per_mil_scal <-  samtools_rpkm$sum_reads/1000000

#2 Divide the read counts by the “per million” scaling factor. This normalizes for sequencing depth, giving you reads per million (RPM)

samtools_rpkm$rpm <-  samtools_rpkm$numreads/samtools_rpkm$reads_per_mil_scal

#3 Divide the RPM values by the length of the gene, in kilobases. This gives you RPKM.
#first convert bp to kbp 

samtools_rpkm$kbp_length <- samtools_rpkm$endpos/1000
samtools_rpkm$RPKM <- samtools_rpkm$rpm/samtools_rpkm$kbp_length


samtools_rpkm2 <- left_join(virome_metadata, samtools_rpkm, by = "filename")




 #Grouping dataframe by treatment and family and summing relative abundances within each subgroup 
plot_df_rpkm <- ggplot(samtools_rpkm2 , aes(fill= contigname, y = samtools_rpkm2$RPKM, x=factor(samtools_rpkm2$filename))) +
labs(x="Sample") + labs(y="Relative abundance") + labs(fill="family") + 
geom_bar(position = "fill",stat ="identity")  +
theme(axis.text.x=element_text(angle=90,hjust=1)) +
    scale_fill_manual(values = custom_palette) 


plot_df_rpkm + theme_classic() +
  theme(text=element_text(family="Arial", face="bold", size=15)) + theme(axis.text.x = element_text(size = 3)) + 
  
  theme(legend.text = element_text(size = 2),
        legend.title = element_text(size = 2)) 


#sanity check - trends look the same 


#now calculate the ratio between amboise and main 

samtools_rpkm_amb <- samtools_rpkm2[samtools_rpkm2$contigname == "ON453899.1_Clostridium_phage_Amboise__complete_genome",]
samtools_rpkm_main <- samtools_rpkm2[samtools_rpkm2$contigname == "ON453900.1_Clostridium_phage_Maintenon__complete_genome",]

samtools_rpkm_amb$amboise  <-  samtools_rpkm_amb$RPKM  
 samtools_rpkm_main$maintenon <- samtools_rpkm_main$RPKM

samtools_rpkm_amb2 <- samtools_rpkm_amb %>%
  select(Day, filename, amboise)

samtools_rpkm_main2 <- samtools_rpkm_main %>%
    select(Day, filename, maintenon)

comb_rpkm_amb_main <- left_join(samtools_rpkm_amb2,samtools_rpkm_main2, by = "filename" )
comb_rpkm_amb_main$ratio <- comb_rpkm_amb_main$amboise/comb_rpkm_amb_main$maintenon
sort(comb_rpkm_amb_main$ratio)

```

```{r}
#write.csv(comb_rpkm_amb_main, "/Users/anshul.sinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome /lb_prophages_list_analyses/samtools/prism/rpkm_amboise_maintenon_ratio.csv")

```




```{r}
#sanity_check - num reads
 numreads <- samtools %>%
    group_by(filename) %>%
    dplyr::summarise(sum_reads = sum(numreads), numreads)




```

```{r}
##PHYLOSEQ### 


#Use the function below that I wrote for the HMP-2 dataset to convert the samtools output to an OTU table that can be used for Phyloseq

##Removing the 

library(phyloseq)
library(dplyr)

#Creating a function that converts the samtools outputs to a matrix that can be used by Phyloseq 
#option to choose "meandepth" (length normalized read counts) or raw read counts "numreads"

ps_otu_tab_maker <- function(sam_tools_output, reads) {
  
  
  
  #read in and select necessary columns for ps 
  
sam_tools_output_1 <- sam_tools_output %>%
  select(filename, contigname, reads)
sam_tools_output_1




if(reads == "meandepth") {
sam_tools_output_1$meandepth <- round(sam_tools_output_1$meandepth, 0)
}  
  else if (reads == "numreads")
{sam_tools_output_1$numreads <- round(sam_tools_output_1$numreads, 0)

}   else {sam_tools_output_1$corrected_reads <- round(sam_tools_output_1$corrected_reads, 0)   } 



#round the decimals - necssary for ps 
#sam_tools_output_1$meandepth <- round(sam_tools_output_1$meandepth, 0)

#sam_tools_output_1


# turn this into a correct format for ps 


sam_tools_output_2 <- sam_tools_output_1 %>%
                 pivot_wider(names_from = filename, values_from = reads)

#replace nas in the df with 0 

sam_tools_output_2[is.na(sam_tools_output_2)] = 0
#sam_tools_output_2

#make the contig column the rownames
 sam_tools_output_3 <- sam_tools_output_2 %>%
  tibble::column_to_rownames("contigname") 
 
# Convert to matrix

sam_tools_matrix <- as.matrix(sam_tools_output_3)
 sam_tools_matrix


}





#choose the "mean depth" option so that we get length normalized reads 

 
otu_table_ps_lb_virome <-  ps_otu_tab_maker(samtools_final, reads = "meandepth")
otu_table_ps_lb_virome_read_test <-  ps_otu_tab_maker(samtools_final, reads = "numreads")




ps_otu_tab_maker2 <- function(sam_tools_output, reads) {
  
  
  
  #read in and select necessary columns for ps 
  
sam_tools_output_1 <- sam_tools_output %>%
  select(filename, contigname, reads)
sam_tools_output_1


sam_tools_output_2 <- sam_tools_output_1 %>%
                 pivot_wider(names_from = filename, values_from = reads)


}



x <- ps_otu_tab_maker2(samtools_final, reads = "meandepth")

 samtools_final
 
 
 # Recreate the wide table explicitly from samtools_final
wide_check <- samtools_final %>%
  select(filename, contigname, meandepth) %>%
  pivot_wider(names_from = filename, values_from = meandepth)

# Compare your function output x to the reference wide_check
identical(x, wide_check)                     # strict check
isTRUE(all.equal(x, wide_check)) 
otu_table_ps_lb_virome


otu_table_ps_lb_virome
wide_check

samtools
otu_table_ps_lb_virome
```









```{r}
#Taxa for PS

omm12_taxa_virome <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_taxonomy.csv")


omm12_taxa_virome <- omm12_taxa_virome %>% 
tibble::column_to_rownames("contigname")

omm12_taxa_virome <- as.matrix(omm12_taxa_virome)
omm12_taxa_virome

# metadata for PS 

#read in metadata - only difference here is im making filename the rowname

virome_metadata_1 <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/virome_metadata.csv", header = TRUE)

#factor levels 
virome_metadata_1$Treatment <- factor(virome_metadata_1$Treatment, levels = c("control", "colitis"))


virome_metadata_1 <- virome_metadata_1 %>% 
tibble::column_to_rownames("filename")


```





```{r}
#PS object for the virome 


#read in metadata - only difference here is im making filename the rowname

virome_metadata_1 <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/virome_metadata.csv", header = TRUE)

#factor levels 
virome_metadata_1$Treatment <- factor(virome_metadata_1$Treatment, levels = c("control", "colitis"))


virome_metadata_1 <- virome_metadata_1 %>% 
tibble::column_to_rownames("filename")
#read in metadata - only difference here is im making filename the rowname

virome_metadata_1 <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/virome_metadata.csv", header = TRUE)

#factor levels 
virome_metadata_1$Treatment <- factor(virome_metadata_1$Treatment, levels = c("control", "colitis"))


virome_metadata_1 <- virome_metadata_1 %>% 
tibble::column_to_rownames("filename")


library("phyloseq")
OTU_OMM12_V = otu_table(otu_table_ps_lb_virome, taxa_are_rows = TRUE)
TAX_OMM12_V = tax_table(omm12_taxa_virome)
META_OMM12_V <- sample_data(virome_metadata_1)

#sample_names(virome_metadata_1) <- virome_metadata_1$filename

PS_OMM12_V = phyloseq(OTU_OMM12_V, TAX_OMM12_V, META_OMM12_V)
PS_OMM12_V

sample_sums(PS_OMM12_V)


```


```{r}
#sanity check to compare with samtools 

psmelt_sanity <- ps_melt(PS_OMM12_V)



#PS1 
comp_barplot(PS_OMM12_V, n_taxa =12, tax_level = "Species", sample_order = "bray")

comp_barplot(PS_OMM12_V, n_taxa =12, tax_level = "Species", sample_order = "bray",group_by = "Peak_colitis")




```
```{r}
#Check sequencing depth saturation



sample_sums(PS_OMM12_V)
# --- 2. Create rarefaction curve (vegan::rarecurve wrapped in phyloseq) ---
otu_mat_virome <- as(otu_table(PS_OMM12_V), "matrix")
if (taxa_are_rows(PS_OMM12_V)) {
  otu_mat_virome <- t(otu_mat_virome)
}



# vegan's rarecurve function
vegan::rarecurve(
  otu_mat_virome,
  step = 20,
  sample = 400,
  label = FALSE,
  xlim = c(0, 20000)
)

#Some samples have low depth but lets see if this is an issue by looking at the good's coverage 

#Low depth should be fine so long 



ps_melt_virome_OMM12 <-  ps_melt(PS_OMM12_V) 




 goods.data.virome.omm12 <- ps_melt_virome_OMM12 %>% 
  group_by(Sample) %>%
  summarise(nseqs= sum(Abundance),
            n_singletons = sum(Abundance == 1), 
            goods = 100*(1- n_singletons/nseqs)) 

goods.data.virome.omm12.plot <- goods.data.virome.omm12 %>% 
  ggplot(aes(x = nseqs, y = goods)) +
  geom_point() +
  scale_y_continuous(limits = c(0, 100))

goods.data.virome.omm12 <- na.omit(goods.data.virome.omm12)

mean(goods.data.virome.omm12$goods) #98.59
median(goods.data.virome.omm12$goods) #100 - and high Good's 
min(goods.data.virome.omm12$goods) #99.091


```

```{r}
#95% of min sampled reads 
sample_sums(PS_OMM12_V)


rarefied_reads_1_v <-  rarefy_even_depth(PS_OMM12_V, rngseed=1, sample.size=0.95*min(sample_sums(PS_OMM12_V)), replace=F)

sample_sums(rarefied_reads_1_v)
# --- 2. Create rarefaction curve (vegan::rarecurve wrapped in phyloseq) ---
otu_mat <- as(otu_table(rarefied_reads_1_v), "matrix")
if (taxa_are_rows(rarefied_reads_1_v)) {
  otu_mat <- t(otu_mat)
}

# vegan's rarecurve function
rarecurve_list <- vegan::rarecurve(
  otu_mat,
  step = 20,
  sample = 400,
  label = FALSE
)

#despite only rarefying at 210, still there seems to be saturation... 


#calculate Good's coveage

ps_melt_virome <-  ps_melt(rarefied_reads_1_v) 




 goods.data.virome <- ps_melt_virome %>% 
  group_by(Sample) %>%
  summarise(nseqs= sum(Abundance),
            n_singletons = sum(Abundance == 1), 
            goods = 100*(1- n_singletons/nseqs)) 

goods.plot.virome <- goods.data.virome %>% 
  ggplot(aes(x = nseqs, y = goods)) +
  geom_point() +
  scale_y_continuous(limits = c(0, 100))

goods.data.virome <- na.omit(goods.data.virome)

mean(goods.data.virome$goods) #99.25
median(goods.data.virome$goods) #99.04 - and high Good's 



```






```{r}
#instead of doing this by rarefying with few reads for some samples - try this by normalizing by relative abundance
#This is new change as of 11_2025 - will keep for manuscript


 cols_treats <- c("blue","red")
sample_sums(PS_OMM12_V)

#first subset to get just the time points of interest 
 subsetps1 <- subset_samples(PS_OMM12_V, Days_Post_DSS == "0" | Days_Post_DSS == "8" | Days_Post_DSS == "9" | Days_Post_DSS == "12" | Days_Post_DSS == "19" )

#now normalize by total sum scaling 
ps_rel <- transform_sample_counts(subsetps1, function(x) x / sum(x))

sample_sums(ps_rel)


#sanity 







#validate the relab worked 
mattest2 <- as(otu_table(ps_rel), "matrix")
colSums(mattest2)
mattest2

sample_data(ps_rel)$Days_Post_DSS <- factor(sample_data(ps_rel)$Days_Post_DSS)

ps_pcoa <- ordinate(ps_rel, method = "PCoA", distance = "bray")



plot_ordination(ps_rel, ps_pcoa, type = "samples",
                color = "Treatment", shape = "Days_Post_DSS") +
  geom_point(size = 8) +
  scale_color_manual(
    name = "Treatment",
    values = c("control" = "blue", "colitis" = "red"),
    labels = c("Control", "Colitis")
  ) +
  theme_minimal() +
  theme(
    panel.grid = element_blank(),                 # remove gridlines
    axis.line = element_line(color = "black", size = 0.8),  # solid axes
    panel.border = element_blank(),
    
    legend.title = element_text(size = 16),       # increase legend title size
    legend.text  = element_text(size = 14)        # increase legend label size
  ) +
  guides(
    shape = guide_legend(title = "Days Post DSS"),
    color = guide_legend(title = "Treatment")
  )
 

plot_ordination(ps_rel, ps_pcoa, type = "samples",
                color = "Treatment", shape = "Days_Post_DSS")



p <- plot_ordination(ps_rel, ps_pcoa, type = "samples")

df_testcheck <- as.data.frame(p$data)
df_testcheck$SampleID <- rownames(df_testcheck)



ggplot(df_testcheck, aes(x = Axis.1, y = Axis.2, label = SampleID)) +
  geom_text(size = 3)


 PCoA_rel_2 <- ps_rel  %>%
     dist_calc("bray") %>%
  ord_calc("PCoA") %>%
  ord_plot(color = "Treatment", shape = "Days_Post_DSS", size = 4) +
       scale_colour_manual(labels = c("Control", "Colitis"), values = cols_treats)  
 PCoA_rel_2 + theme_bw()  + 
  labs(shape="Days_Post_DSS", color="Treatment") + 
   theme(panel.grid.major = element_blank(),
panel.grid.minor = element_blank()) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_text(size = 16),  # Adjust X-axis title size
    axis.title.y = element_text(size = 16), 
    legend.text = element_text(size=16),
    legend.title = element_text(size = 18),   # Adjust legend title size
    plot.title = element_text(size = 16)      # Adjust plot title size
  ) +
  guides(
    shape = guide_legend(title = "Days Post DSS"),  # Change legend title for shape
    color = guide_legend(title = "Treatment")       # Keep legend title for color
  )
 
 ps_pcoa
 
 #The two PCoAs look very similar - slight difference in %variance - may be due to Microviz wrapper for vegan 
 # in general - both look quite similar to 


 
 
```






```{r}
#Relative Abundance Plots 
#PS_Melt 
OMM12_V_melt_subset <- ps_melt(subsetps1)
#remove a. muris 
OMM12_V_melt_subset2 <- OMM12_V_melt_subset[OMM12_V_melt_subset$OTU != "ON453893.1_Acutalibacter_phage_Fontainebleau__complete_genome",]

# Calculate relative abundance
OMM12_V_melt_subset_relab <- OMM12_V_melt_subset2 %>%
  group_by(Sample) %>%
  mutate(RelativeAbundance = Abundance / sum(Abundance))



#create facet order 
OMM12_V_melt_subset_relab$CombinedOrder <- factor(paste(OMM12_V_melt_subset_relab$Days_Post_DSS, OMM12_V_melt_subset_relab$Treatment), levels = c("0 control", "0 colitis","8 control", "8 colitis", "9 control", "9 colitis", "12 control", "12 colitis", "19 control", "19 colitis"))





#For plotting purposes, remove the "D" and "C" of the plot 
OMM12_V_melt_subset_relab$Mouse <- substring(OMM12_V_melt_subset_relab$Mouse, 2)



OMM12_V_melt_subset_relab$OTU <- factor(OMM12_V_melt_subset_relab$OTU, levels = unique(sort(OMM12_V_melt_subset_relab$OTU)))


# Get unique levels of the "Category" variable
unique_vOTU <- unique(OMM12_V_melt_subset_relab$OTU)

OTU_colors_virus <- c("#FF0500", "#FF817E", "#FFCCCB", "#C1E1C1", "orange", "#3e236e", "#d6b4fc", "#DEC20B", "#F2E6B1", "grey", "darkgrey", "black", "white" )  
      


library(ggplot2)

# Your original data
# ...

#paste in "phage"

OMM12_V_melt_subset_relab$Genus_Species <- paste(OMM12_V_melt_subset_relab$Genus, "-", sep = "_")

# Combine Genus and Species into Genus_Species
OMM12_V_melt_subset_relab$Genus_Species <- paste(OMM12_V_melt_subset_relab$Genus_Species, OMM12_V_melt_subset_relab$Species, sep = "_")

# Convert Genus_Species to a factor and order alphabetically
OMM12_V_melt_subset_relab$Genus_Species <- factor(OMM12_V_melt_subset_relab$Genus_Species, levels = sort(unique(OMM12_V_melt_subset_relab$Genus_Species)))

# Create custom labels without underscores
legend_labels <- gsub("_", " ", levels(OMM12_V_melt_subset_relab$Genus_Species))





# with legend 
ggplot(OMM12_V_melt_subset_relab, aes(x = Mouse, y = RelativeAbundance, fill = Genus_Species)) +
  geom_bar(stat = "identity") +
  labs(title = "", x = "Sample", y = "Relative Abundance") +
  theme_minimal() + 
  theme(
    legend.text = element_text(size = 10, face = "italic"),  # Adjust the size and make it italic
    legend.title = element_text(size = 12),
    axis.text.x = element_text(size = 14, angle = 0, hjust = 1),  # Angle the x-axis labels
    axis.text.y = element_text(size = 14),  # Increase the size of y-axis labels
    strip.text = element_blank(),  # Remove strip (facet) labels
    strip.background = element_blank(),     # Remove strip background
    strip.placement = "outside"              # Place strip labels outside the plot
  ) +
  scale_fill_manual(values = OTU_colors_virus, labels = legend_labels) +  # Use custom labels without underscores
  guides(fill = guide_legend(title = "Genus Species")) +  # Legend title without underscores
  labs(fill = "Legend Label")  + 
  facet_grid(~CombinedOrder, scales = "free")


# without legend 
ggplot(OMM12_V_melt_subset_relab, aes(x = Mouse, y = RelativeAbundance, fill = Genus_Species)) +
  geom_bar(stat = "identity") +
  labs(title = "", x = "Sample", y = "Relative Abundance") +
  theme_minimal() + 
  theme(
    legend.text = element_text(size = 0, face = "italic"),  # Adjust the size and make it italic
    legend.title = element_text(size = 0),
    axis.text.x = element_text(size = 14, angle = 0, hjust = 1),  # Angle the x-axis labels
    axis.text.y = element_text(size = 14),  # Increase the size of y-axis labels
    strip.text = element_blank(),  # Remove strip (facet) labels
    strip.background = element_blank(),     # Remove strip background
    strip.placement = "outside"              # Place strip labels outside the plot
  ) +
  scale_fill_manual(values = OTU_colors_virus, labels = legend_labels) +  # Use custom labels without underscores
  guides(fill = guide_legend(title = "Genus Species")) +  # Legend title without underscores
  labs(fill = "Legend Label")  + 
  facet_grid(~CombinedOrder, scales = "free")

```
```{r}
#sanity check: 

df_rel_test <- OMM12_V_melt_subset %>%
  group_by(Sample) %>%
  mutate(RelAbund = Abundance / sum(Abundance)) %>%
  ungroup()


df_rel_test <- df_rel_test %>%
  mutate(
    Days_Post_DSS = factor(Days_Post_DSS,
                           levels = sort(unique(Days_Post_DSS))),
    Mouse = factor(Mouse, levels = sort(unique(Mouse)))
  )


ggplot(df_rel_test,
       aes(x = Mouse, y = RelAbund, fill = OTU)) +
  geom_col(width = 0.8, colour = "grey20") +
  facet_grid(Treatment ~ Days_Post_DSS,
             space = "free_x", scales = "free_x") +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "Mouse ID",
       y = "Relative Abundance",
       fill = "Virus") +
  theme_bw() +
  theme(
    panel.spacing = unit(0.6, "lines"),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)
  )

```



```{r}


library(stringr)



```

```{r}

#Get relative abundance from PS object - do this on non rarefied data 

ps_melt(PS_OMM12_V)


relative_abundance_virome <-   PS_OMM12_V %>% 
      tax_glom(taxrank = "Species") %>% 
        transform_sample_counts(function(x) {x/sum(x)}) %>% 
        psmelt() %>%
        select(Species, Sample, Abundance) %>%
        spread(Sample, Abundance)



        
        
        

```

```{r}



```




```{r}
#calculate bray distances by day 

#NOTE DAY 9 = DAY 0 POST DSS 
# DAT 17 = DAY 8 POST-DSS 
#DAY 18 = DAY 9 POST-DSS 
# DAY 21 = DAY 12 POST-DSS
#DAY 28 = DAY 28 POST-DSS 

#Similar to the PCoA: Calculate Bray on Relative Abundance-normalized data
#Take the subsetted ps1 to only take the dates of interest 


ps_rel2 <- transform_sample_counts(subsetps1, function(x) x / sum(x))



ps2_9_v <- subset_samples(ps_rel2,Day == "9")
ps2_17_v <- subset_samples(ps_rel2, Day == "17")
ps2_18_v <- subset_samples(ps_rel2, Day == "18")
ps2_21_v <- subset_samples(ps_rel2, Day == "21")
ps2_28_v <- subset_samples(ps_rel2, Day == "28")




#getting dist matrices for rarefied counts 


ps2_9_dist_v  <- as.matrix(phyloseq::distance(ps2_9_v, method = "bray"))

ps2_17_dist_v  <- as.matrix(phyloseq::distance(ps2_17_v, method = "bray"))

ps2_18_dist_v  <- as.matrix(phyloseq::distance(ps2_18_v, method = "bray"))

ps2_21_dist_v  <- as.matrix(phyloseq::distance(ps2_21_v, method = "bray"))

ps2_28_dist_v  <- as.matrix(phyloseq::distance(ps2_28_v, method = "bray"))
class(ps2_9_dist_v)


write.csv(ps2_9_dist_v, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/diversity/dist9.csv")


write.csv(ps2_17_dist_v, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/diversity/dist17.csv")

write.csv(ps2_18_dist_v, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/diversity/dist18.csv")

write.csv(ps2_21_dist_v, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/diversity/dist21.csv")

write.csv(ps2_28_dist_v, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/diversity/dist28.csv")
```












```{r}
#STABILITY CALCULATIONS 
#calculate stability as 1-Bray Dist - for each mouse at successive time points 


#step 1 - calculate bray-dist between all samples 

#all_samples_bray <- bray_dist_matrix(rar_subsetted_ps1_v)

#step 2 Melt and rename columns
 
 #melted_all_samples_bray <- all_samples_bray  %>%
 #  melt()

 
 #colnames(melted_all_samples_bray) <- c("sample1", "sample2", "dist.bray")

 
 

#step 3 calculate stability as 1-bray 
 
 #melted_all_samples_bray$stability <- 1-melted_all_samples_bray$dist.bray
#
 
#step 4 - adjust and join the metadatas join with metadata - need to distinguish the metadata cols for each 
 
 #for purposes of plotting by time, I think I need to create a time interval column so that time points are "evenly spaced"
 
 # Create a new column with adjusted values
#virome_metadata_1 <- virome_metadata %>%
 # mutate(time_interval = case_when(
 #   Days_Post_DSS == 8  ~ 1,
  #  Days_Post_DSS == 9  ~ 2,
  #  Days_Post_DSS == 12  ~ 3,
   # Days_Post_DSS ==  19 ~ 4,
   # TRUE ~ Days_Post_DSS  # For all other values, keep the same as 'days-post DSS'
 # ))
 


#note that with these modifications to the metadata, it will only work if removing samples from dpd 1 and 7



 
 
 #change the cols for sample1
 #virome_metadata_sample1 <- virome_metadata_1
 #colnames(virome_metadata_sample1) <- c("filename_s1", "Mouse_s1", "Day_s1", "Treatment_s1", "Peak_colitis_s1", "Days_post_DSS_s1", "sample1", "interval_s1")
                                        
 
  #virome_metadata_sample2 <- virome_metadata_1

 #colnames(virome_metadata_sample2) <- c("filename_s2", "Mouse_s2", "Day_s2", "Treatment_s2", "Peak_colitis_s2", "Days_post_DSS_s2", "sample2", "interval_s2")
                                        
 

 #dist.merged.all_1 <- left_join(melted_all_samples_bray, virome_metadata_sample1, by= "sample1")
 #now join with the sample 2 metadata 
 #dist.merged.all <- left_join(dist.merged.all_1,virome_metadata_sample2, by="sample2" )


                              
#remove samples where sample 1 = sample2 

#dist.merged.all_1 <- dist.merged.all[!dist.merged.all$sample1 == dist.merged.all$sample2,]
#remove samples where samples are from day 1 or 7 post-dss 

#dist.merged.all_2 <- dist.merged.all_1[!dist.merged.all_1$Days_post_DSS_s1 == 1 | dist.merged.all_1$Days_post_DSS_s1 == 7 | dist.merged.all_1$Days_post_DSS_s2 == 1 | dist.merged.all_1$Days_post_DSS_s2 == 7,]
                                      
                                         
#There should be duplicates for the distance calculations - so... deal with that here 

#dist.merged.all_2 <- dist.merged.all_2 %>% 
 # mutate(timepoint_after = interval_s2 > interval_s1) %>%  # Time_point.sample2 > Time_point.sample1
  #filter(timepoint_after) 

#dist.merged.all_2



#now I need to only include the distance between the same mouse 


#dist.merged.same.mouse = dist.merged.all_2[dist.merged.all_2$Mouse_s1 == dist.merged.all_2$Mouse_s2,]



###STABILITY FROM BASELINE 
#for this - we can only include this if interval_s1 is 0
#dist.merged.same = dist.merged.same.mouse[dist.merged.same.mouse$interval_s1 == 0,]

# Create the plot
#ggplot(dist.merged.same, aes(x = Days_post_DSS_s2, y = stability, color = Treatment_s2, group = Mouse_s2)) +
# geom_line(size = 1) +       # Line plot for each mouse
 # geom_point(size = 3) +      # Points for each observation
 ## labs(title = "Stability over Days Post DSS",
     #  x = "Days Post DSS",
    #   y = "Stability from Baseline",
     #  color = "Mouse") +     # Legend title for mice
  #theme_minimal() +           # Minimal theme for clean look
  #theme(legend.position = "right")  # Adjust legend position if necessary


#SAME BUT JUST CONTROL
#dist.merged.same = dist.merged.same.mouse[dist.merged.same.mouse$interval_s1 == 0,]
#dist.merged.same_control = dist.merged.same[dist.merged.same$Treatment_s1 == "control",]
# Create the plot
#ggplot(dist.merged.same_control, aes(x = Days_post_DSS_s2, y = stability, color = Treatment_s2, group = Mouse_s2)) +
# geom_line(size = 1, color = "blue") +       # Line plot for each mouse
 # geom_point(size = 3) +      # Points for each observation
 # labs(title = "Stability over Days Post DSS",
      # x = "Days Post DSS",
     #  y = "Stability from Baseline",
       #color = "Mouse") +     # Legend title for mice
  #theme_minimal() +           # Minimal theme for clean look
  #theme(legend.position = "right")  # Adjust legend position if necessary



###STABILITY BETWEEN SUCCESSIVE TIME POINTS - JUST CONTROL 

#dist.merged.timepoints = dist.merged.same.mouse[dist.merged.same.mouse$interval_s2 - dist.merged.same.mouse$interval_s1 == 1,]


# Create the plot
#ggplot(dist.merged.timepoints, aes(x = Days_post_DSS_s2, y = stability, color = Treatment_s2, group = Mouse_s2)) +
#  geom_line(size = 1) +       # Line plot for each mouse
 # geom_point(size = 3) +      # Points for each observation
 # labs(title = "Stability over Days Post DSS",
  #     x = "Days Post DSS",
  #     y = "Stability from Baseline",
  #     color = "Mouse") +     # Legend title for mice
 # theme_minimal() +           # Minimal theme for clean look
  #theme(legend.position = "right")  # Adjust legend position if necessary


###SAME BUT JUST CONTROL

#dist.merged.timepoints_ctrl <- dist.merged.timepoints[dist.merged.timepoints$Treatment_s1 == "control",]
#dist.merged.timepoints_ctrl = dist.merged.timepoints_ctrl[dist.merged.timepoints_ctrl$interval_s2 - dist.merged.timepoints_ctrl$interval_s1 == 1,]
# Create the plot
#ggplot(dist.merged.timepoints_ctrl, aes(x = Days_post_DSS_s2, y = stability, color = Treatment_s2, group = Mouse_s2)) +
  #geom_line(size = 1, colour = "blue") +       # Line plot for each mouse
  #geom_point(size = 3) +      # Points for each observation
#  labs(title = "Stability over Days Post DSS",
     #  x = "Days Post DSS",
   #    y = "Stability from Baseline",
     #  color = "Mouse") +     # Legend title for mice
  #theme_minimal() +           # Minimal theme for clean look
  #theme(legend.position = "right")  # Adjust legend position if necessary






```

```{r}
#Calculate Cage effects over time 

#distances should not be between the same mouse 

#dist.merged.all_2_vir_cage <- dist.merged.all[dist.merged.all$Mouse_s1 != dist.merged.all$Mouse_s2.x,]

#distances should just be between control mice

#dist.merged.all_2_vir_cage <- dist.merged.all_2_vir_cage[dist.merged.all_2_vir_cage$Treatment_s1 == "control",]
#dist.merged.all_2_vir_cage <- dist.merged.all_2_vir_cage[dist.merged.all_2_vir_cage$Treatment_s2.x == "control",]



#distances should just be on the same day 

#dist.merged.all_2_vir_cage_test <- dist.merged.all_2_vir_cage[dist.merged.all_2_vir_cage$Day_s1 == dist.merged.all_2_vir_cage$Day_s2.x,]




#remove duplicate 
#dist.merged.all_2_vir_cage_test <- dist.merged.all_2_vir_cage_test %>%
 # sample_frac(1) %>%
 # distinct(dist.bray, .keep_all = TRUE)

#write.csv(dist.merged.all_2_vir_cage_test, "/Users/anshulsinha/Desktop/test/cage_distance_vir.csv")





# Step 1: Calculate the mean and standard deviation of stability for each day
#stats_cage_stability_vir <- dist.merged.all_2_vir_cage_test %>%
#  group_by(Days_post_DSS_s2.x) %>%
 # summarise(mean_stability = mean(stability),
  #          sd_stability = sd(stability))


# Step 1: Calculate the mean and standard deviation of dist.bray for each day
#stats_cage_bray_vir <- dist.merged.all_2_vir_cage_test %>%
 # group_by(Days_post_DSS_s2.x) %>%
  #summarise(mean_bray = mean(dist.bray),
  #          sd_bray = sd(dist.bray))

#cage stability 

#ggplot(stats_cage_stability_vir, aes(x = Days_post_DSS_s2.x, y = mean_stability)) +
#  geom_line(color = "blue") +             # Line for stability
#  geom_point(color = "blue") +            # Points for stability
#  geom_errorbar(aes(ymin = mean_stability - sd_stability, ymax = mean_stability + sd_stability), 
   #             width = 0.2, color = "red") + # Error bars for SD
 # labs(title = "Cage Stability Over Time", 
  #     x = "Time", 
  #     y = "Stability") +
#  theme_minimal()

#cage distance


#ggplot(stats_cage_bray_vir, aes(x = Days_post_DSS_s2.x, y = mean_bray)) +
 # geom_line(color = "blue") +             # Line for stability
  #geom_point(color = "blue") +            # Points for stability
  #geom_errorbar(aes(ymin = mean_bray - sd_bray, ymax = mean_bray + sd_bray), 
   #             width = 0.2, color = "red") + # Error bars for SD
  #labs(title = "Distance Between Cages", 
  #     x = "Time", 
  #     y = "Stability") +
  #theme_minimal()

```




```{r}
####DESEQ2#### - Im going to use num reads instead of mean depth since length correcting reads isnt important here since we are looking at how these change between groups 


#Using the df_relab df which contains the raw read counts (its just the modified samtools_final)

df_relab

#going to just focus on pre vs. post colitis (days 9. 17, 18)

df_relab_subset <- df_relab[df_relab$Day == 9 | df_relab$Day == 17 | df_relab$Day == 18,]


#For Deseq2 convert to a matrix with contig name 





samtools_lb <- df_relab_subset[, c("filename", "contigname", "numreads")]
samtools_lb

library(dplyr)
library(tidyr)
library(tidyverse)
library(data.table)


#use tiydrpivot wider 

deseq_matrix_lb <-  tidyr::pivot_wider(samtools_lb, names_from = contigname, values_from = numreads)
deseq_matrix_lb



#switching the columns and rows so that each row is a different contig and each column is a different sample 
switched_matrix_lb <-  t(deseq_matrix_lb)



switched_matrix_lb



#export this 
write.csv(switched_matrix_lb, "/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/deseq2/switched_matrix.csv") 



```




```{r}
#reading in manually edited switched matrix

raw_counts2_lb <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/reanlayses_11_2025/deseq2/switched_matrix_edit.csv", check.names = FALSE)
raw_counts2_lb



#Formatting the rawcount2_deseq2 transposed matrix 



colnames(raw_counts2_lb)[1] <- "contig_ID"

raw_counts2_lb


#replace NA values with 0
raw_counts2_lb[is.na(raw_counts2_lb)] = 0
raw_counts2_lb

#naming that column "contig_ID"

contig_ID_lb <-  raw_counts2_lb$contig_ID

#Now I am generating a "sample index" so I can exclude "contig_ID" from our matrix 

sample_index_lb <- grepl("\\d", colnames(raw_counts2_lb))
##of the column names, anything that contains a numeric 


#converting to a matrix and only including the sample index columns 
raw_counts_lb_matrix <- as.matrix(raw_counts2_lb[,sample_index_lb])
raw_counts_lb_matrix


rownames(raw_counts_lb_matrix) <- contig_ID_lb

head(raw_counts_lb_matrix)

```


```{r}
#reading in sample mapping file (coldata)
sample_mapping_lb <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_list_analyses/deseq2/sample_mapping_virome_deseq_subset.csv", row.names = 1)

sample_mapping_lb

#changing all columns to factor 
sample_mapping_lb <- mutate_if(sample_mapping_lb, is.character, as.factor)
sample_mapping_lb <- mutate_if(sample_mapping_lb, is.integer, as.factor)
sample_mapping_lb

class(sample_mapping_lb$mouseID_n)
```
```{r}
#note that the row.names dont have a column name - this is consistent with how coldata is shown in the deseq2 vignette 


sample_mapping_lb

levels(sample_mapping_lb$Treatment)
levels(sample_mapping_lb$Condition1)
sample_mapping_lb$Condition1  <-relevel(sample_mapping_lb$Condition1, ref="pre_col")

#Put the columns of the count data in the same order as rows names of the sample mapping, then make sure it worked (TRUE)
all(colnames(raw_counts_lb_matrix) %in% rownames(sample_mapping_lb))  # TRUE = all matrix cols found in metadata

raw_counts_lb_matrix <- raw_counts_lb_matrix[, unique(rownames(sample_mapping_lb))]




all(colnames(raw_counts_lb_matrix) == rownames(sample_mapping_lb))

sample_mapping_lb
colnames(raw_counts_lb_matrix)
rownames(sample_mapping_lb)

## 1          X        1        A
## 2          X        1        B
```

```{r}

library(DESeq2)
#starting the object construction with a simple design per vignette 


deseq2Data_lb <- DESeqDataSetFromMatrix(countData=raw_counts_lb_matrix, colData=sample_mapping_lb, design = ~ mouseID + Condition1)
mcols(deseq2Data_lb)

head(sample_mapping_lb)

head(raw_counts_lb_matrix)
```

```{r}
#relevelling the condition and treatment variables so that the ref is pre-col -
# relevelling the sample_mapping seems necessary, so that when we build the model.matrix, it contains the Treatment:Post_col values and not Treatment:Pre_col values 




deseq2Data_lb <- DESeqDataSetFromMatrix(countData=raw_counts_lb_matrix, colData=sample_mapping_lb, design = ~ mouseID + Condition1)

levels(sample_mapping_lb$Condition1)



#creating more complex design - controlling for cage, looking at Treatment specific (ie- control vs. colitis group effect of colitis induction)


mm_lb <- model.matrix(~ Treatment + Treatment:mouseID_n + Treatment:Condition1, sample_mapping_lb)
mm_lb



#Running DESeq with the new model matrix 


deseq2Data_lb = DESeq(deseq2Data_lb, full = mm_lb, betaPrior = FALSE)





design(deseq2Data_lb)

qr(mm_lb)$rank
ncol(mm_lb)
```
```{r}
#test 
deseq2Data_lb_test <- DESeqDataSetFromMatrix(countData=raw_counts_lb_matrix, colData=sample_mapping_lb, design = ~ Treatment + Treatment:mouseID_n + Treatment:Condition1)


deseq2Data_lb_test2 <- DESeq(deseq2Data_lb_test)
resultsNames(deseq2Data_lb_test2)
deseq2_results_lb_test <-  results(deseq2Data_lb_test2, contrast=list("Treatmentcolitis.Condition1post_col","Treatmentcontrol.Condition1post_col"))
summary(deseq2_results_lb_test)


deseq2_results_lb_test2 <- as.data.frame(deseq2_results_lb_test)
deseq2_results_lb_sig2 <- subset(deseq2_results_lb_test2, padj < 0.05)

```



```{r}

deseq2Data_lb_test3 <- DESeqDataSetFromMatrix(
  countData = raw_counts_lb_matrix,
  colData   = sample_mapping_lb,
  design    = ~ 1   # dummy, will be overridden in DESeq()
)

deseq2Data_lb3 <- DESeq(
  deseq2Data_lb_test3,
  full      = ~ Treatment + Treatment:mouseID_n + Treatment:Condition1,
  betaPrior = FALSE
)
```


```{r}

resultsNames(deseq2Data_lb)
deseq2_results_lb <-  results(deseq2Data_lb, contrast=list("Treatmentcolitis.Condition1post_col","Treatmentcontrol.Condition1post_col"))



deseq2_results_lb <- as.data.frame(deseq2_results_lb)

deseq2_results_lb <- deseq2_results_lb %>% 
rownames_to_column(var = "contigname")
deseq2_results_lb




#remove leading spaces 
deseq2_results_lb$contigname <- trimws(deseq2_results_lb$contigname, "left")




#significant values 

deseq2_results_lb_sig <- subset(deseq2_results_lb, padj < 0.05)


deseq2_results_lb_sig <- as.data.frame(deseq2_results_lb_sig)
deseq2_results_lb_sig

```



```{r}


library(EnhancedVolcano)

#in order to plot the cutoff of padj and not p-value, we need to give the pvalue column in the df the values from the padj column 


deseq2_results_lb1 <- deseq2_results_lb
deseq2_results_lb1$pvalue <- deseq2_results_lb1$padj


keyvals_col_con_lb <- ifelse(
    deseq2_results_lb1$log2FoldChange < -1 & deseq2_results_lb1$padj < 0.05, 'blue',
      ifelse(deseq2_results_lb1$log2FoldChange > 1 & deseq2_results_lb1$padj < 0.05, 'red',
        'light grey'))
  keyvals_col_con_lb[is.na(keyvals_col_con_lb)] <- 'light grey'
  names(keyvals_col_con_lb)[keyvals_col_con_lb == 'red'] <- 'Over-Abundant in Colitis Group'
  names(keyvals_col_con_lb)[keyvals_col_con_lb == 'light grey'] <- 'Non-significant'
  names(keyvals_col_con_lb)[keyvals_col_con_lb == 'blue'] <- 'Over-Abundant in Control'

EV_col_con_lb <- EnhancedVolcano(deseq2_results_lb1, lab=NA , x = 'log2FoldChange',
    y = 'pvalue',  pCutoff = 0.05, cutoffLineWidth = 0.1, selectLab = rownames(deseq2_results_lb1)[which(names(keyvals_col_con_lb) %in% c('Over-Abundant in Colitis', 'Over-Abundant in Control'))], pointSize = 4, gridlines.major = FALSE, gridlines.minor = FALSE, colCustom = keyvals_col_con_lb,  legendPosition = 'right', legendLabSize = 12.5,legendIconSize = 4.0, title = "", axisLabSize = 18,    subtitle = "", caption = ""
)

EV_col_con_lb

```
```{r}
library(ggplot2)



omm12_taxa_virome2 <- read.csv("/Users/anshulsinha/Desktop/IBD_prophages_aim/omm-12/OMM12_DSS_2.0_10_23/seq_analyses/virome/lb_prophages_taxonomy.csv")


# Create a custom shape for a circle
circle <- data.frame(x = 0, y = 0)



#left join 

deseq2_results_lb2 <- left_join(deseq2_results_lb, omm12_taxa_virome2, by="contigname")


deseq2_results_lb2 %>%
  ggplot(aes(x = log2FoldChange, y = interaction(Genus, Species))) +
  geom_vline(xintercept = 0) +
  geom_point(
    aes(
      x = log2FoldChange, 
      y = interaction(Genus, Species), 
      color = ifelse(log2FoldChange > 0, "pastelred", "pastelblue")
    ),
    size = 5
  ) +
  geom_point(
    data = filter(deseq2_results_lb2, padj < 0.05),
    aes(
      x = log2FoldChange,
      y = interaction(Genus, Species),
      color = "red"
    ),
    size = 7,
    shape = 1
  ) +
  scale_color_manual(values = c("pastelblue" = "skyblue", "pastelred" = "lightcoral", "red" = "red")) +
  theme_bw() +
  theme(
    axis.text.y = element_text(size = 7, face = "italic", color = "black"),
    legend.position = "none"  # Remove the legend
    
  ) +
  guides(color = FALSE)  # Remove the legend

```

```{r}
library(forcats)
library(dplyr)
library(forcats)

deseq2_results_lb3 <- deseq2_results_lb2[deseq2_results_lb2$Species != "Fontainebleau",]

deseq2_results_lb3 %>%
  ggplot(aes(x = log2FoldChange, y = reorder(interaction(Genus, Species, sep = ""), -log2FoldChange))) +
  geom_vline(xintercept = 0) +
  geom_point(
    aes(
      x = log2FoldChange, 
      y = reorder(interaction(Genus, Species, sep = " "), -log2FoldChange), 
      color = ifelse(log2FoldChange > 0, "pastelred", "pastelblue")
    ),
    size = 5
  ) +
  geom_point(
    data = filter(deseq2_results_lb3, padj < 0.05 & (log2FoldChange > 1 | log2FoldChange < -1)),
    aes(
      x = log2FoldChange,
      y = reorder(interaction(Genus, Species, sep = " "), -log2FoldChange),
      color = "black"
    ),
    size = 10,
    shape = 1
  ) +
  geom_point(
    data = filter(deseq2_results_lb3, padj >= 0.05),
    aes(
      x = log2FoldChange,
      y = reorder(interaction(Genus, Species, sep = " "), -log2FoldChange),
      color = "grey"
    ),
    size = 5
  ) +
  scale_color_manual(values = c("pastelblue" = "blue", "pastelred" = "red", "red" = "red", "grey" = "grey")) +
  theme_bw() +
  theme(
    axis.text.y = element_text(size = 16, face = "italic", color = "black"),
    axis.text.x = element_text(size = 16, color = "black"), 
    axis.title.x = element_text(size = 16),
    legend.position = "none"
  ) +
  guides(color = FALSE) +
  labs(x = expression(Log[2]~"Fold-Change"))


```


